<style>
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }
    html {
        -webkit-print-color-adjust: white;
    }
    footer {
        border-top: 1px dotted #64748b;
        width: 100%;
        font-size: 14px;
        padding: 48px;
        padding-bottom: 24px;
        color: #27272a;
    }
</style>

<footer>
    <div style="float: left;">
        <p>Generated by: {{ $report->user->name()  }}</p>
        <p>Generated on {{ date_format(date_create($report->created_at), 'F j, Y \a\t h:i A') }}</p>
    </div>

    <div style="width: 100%;"></div>

    <div style="float: right;">Page @pageNumber of @totalPages</div>
</footer>