<?php

namespace App\Livewire\App\Report;

use App\Jobs\GenerateReport;
use App\Models\Report;
use App\Models\RoomType;
use App\Models\User;
use App\Traits\DispatchesToast;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Livewire\Attributes\On;
use Livewire\Attributes\Validate;
use Livewire\Component;

class CreateReport extends Component
{
    use DispatchesToast;

    public $min_date;
    public $max_date;
    
    #[Validate] public $name;
    #[Validate] public $description;
    #[Validate] public $type;
    #[Validate] public $format;
    #[Validate] public $note;
    #[Validate] public $start_date;
    #[Validate] public $end_date;
    #[Validate] public $room_type_id;
    #[Validate] public $size = 'letter';

    public function mount() {
        $this->max_date = Carbon::tomorrow()->format('Y-m-d');
    }

    public function getListeners() {
        return [
            "echo-private:reports." . Auth::user()->id . ",ReportGenerated" => 'automaticDownloadReport',
            "echo:report,ReportGenerated" => 'refreshTable',
            "echo:report,ReportDeleted" => 'refreshTable',
        ];
    }

    public function rules() {
        return [
            'name' => 'required|string|regex:/^[\pL\s\-0-9]+$/u',
            'description' => 'nullable|string',
            'type' => 'required|string',
            'format' => 'required|string',
            'note' => 'nullable|string',
            'start_date' => 'required|date',
            'end_date' => 'required_unless:type,"incoming reservations"|date|nullable',
            'size' => 'required_if:format,PDF',
            'room_type_id' => 'nullable|required_if:type,"occupancy report"'
        ];
    }

    public function messages() {
        return [
            'name.required' => 'Enter the name of your report.',
            'name.regex' => 'File name   must include only letters, numbers, dashes, and spaces.',
            'type.required' => 'Select a type of report.',
            'format.required' => 'Select the format of your report.',
            'start_date.required' => 'Select a start date.',
            'end_date.required_unless' => 'Select an end date.',
        ];
    }

    public function setMinDate($date) {
        $this->min_date = Carbon::parse($date)->addDay()->format('Y-m-d');
    }

    #[On('generate-report')]
    public function setReportType($type) {
        if ($this->type != $type) {
            $this->reset();
        }

        $this->type = $type;
        $this->dispatch('open-modal', 'generate-report');
    }

    public function resetReportType() {
        $this->reset();
    }

    public function store() {
        $validated = $this->validate([
            'name' => $this->rules()['name'],
            'room_type_id' => $this->rules()['room_type_id'],
            'description' => $this->rules()['description'],
            'type' => $this->rules()['type'],
            'format' => $this->rules()['format'],
            'note' => $this->rules()['note'],
            'start_date' => $this->rules()['start_date'],
            'end_date' => $this->rules()['end_date'],
        ]);

        $validated['user_id'] = Auth::user()->id;

        // Store report to database
        $report = Report::create($validated);

        // Update path of the report
        $report->path = $report->format . '/report/' . $report->name . ' - ' . $report->rid . '.' . $report->format;
        $report->save();
        
        // Generate report
        GenerateReport::dispatch($report, $this->size);

        $this->toast('Success!', description: 'Report created');
        $this->dispatch('pg:eventRefresh-ReportsTable');
        $this->dispatch('report-created');
        $this->reset();
    }

    public function automaticDownloadReport($event) {
        $this->toast('Success!', description: 'Your file is ready to download');
        return response()->download(Storage::path('public/' . $event['report']['path']));
    }

    public function refreshTable($event) {
        if ($event['report']['user_id'] != Auth::user()->id) {
            $user = User::find($event['report']['user_id']);
            $this->dispatch('pg:eventRefresh-ReportsTable');
            $this->toast('Success!', description: 'A new report is generated by ' . $user->name());
        }
    }

    public function render()
    {
        $room_types = RoomType::select('id', 'name')->get();

        return view('livewire.app.report.create-report', [
            'room_types' => $room_types,
        ]);
    }
}
